version: '3.8'

services:
  appapi:
    build:
      context: .
      dockerfile: Dockerfile.app
    env_file: .env
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    # command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    volumes:
      - .:/usr/local/chatbot  # Mount project directory for code access
    ports:
      - "8886:8888"
      - "7286:7282"
      - "8000:8000"
      - "7860:7860"
    networks:
      - app-network1
    depends_on:
      - postgresapi
    restart: on-failure

  postgresapi:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: postgrespdf
    ports:
      - "5438:5432"
    env_file: .env
    networks:
      - app-network1
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # Persistent PostgreSQL data
    restart: always

networks:
  app-network1:

volumes:
  postgres-data:
